"""empty message

Revision ID: 1b4c4fcf4f3c
Revises: 7e07720b2c80
Create Date: 2019-03-05 20:43:20.695078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4c4fcf4f3c'
down_revision = '7e07720b2c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_detail', sa.Column('harga', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_detail', 'harga')
    # ### end Alembic commands ###
