"""empty message

Revision ID: 3f0255934632
Revises: 
Create Date: 2019-03-02 20:47:08.727579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f0255934632'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=1), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('user', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', mysql.VARCHAR(length=6), nullable=False))
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
