"""empty message

Revision ID: 65c35cc95ef0
Revises: 1b4c4fcf4f3c
Create Date: 2019-03-10 20:14:07.226415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65c35cc95ef0'
down_revision = '1b4c4fcf4f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('bank', sa.String(length=10), nullable=False))
    op.add_column('seller', sa.Column('date_of_birth', sa.DateTime(), nullable=False))
    op.add_column('seller', sa.Column('no_rekening', sa.String(length=15), nullable=False))
    op.add_column('seller', sa.Column('phone_number', sa.String(length=13), nullable=False))
    op.add_column('seller', sa.Column('provinsi', sa.String(length=30), nullable=False))
    op.drop_column('seller', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('seller', 'provinsi')
    op.drop_column('seller', 'phone_number')
    op.drop_column('seller', 'no_rekening')
    op.drop_column('seller', 'date_of_birth')
    op.drop_column('seller', 'bank')
    # ### end Alembic commands ###
